---
- hosts: node01
  become: true
  tasks:
    - name: create a file
      copy:
        dest: /opt/file.txt
        content: "This file is created by Ansible!"
		
---
- hosts: all
  become: true
  become_user: admin
  tasks:
    - copy:
        src: /usr/src/dba/index.html
        dest: /opt/dba/index.html

#or
# ansible node01 -m copy "src=/etc/resolv.conf dest=/opt/dba/" -i inventory
# ansible-playbook file.yml -i inventory --ask-become-pass #will ask for a sudo password of admin


---
- hosts: all
  become: true
  tasks:
    - name: Copy file with owner and permissions on node01
      copy:
        src: /usr/src/condition/blog.txt
        dest: /opt/condition/blog.txt
        owner: bob
        group: bob
        mode: "0640"
      when: inventory_hostname == "node01"

    - name: Copy file with owner and permissions on node02
      copy:
        src: /usr/src/condition/story.txt
        dest: /opt/condition/story.txt
        owner: sam
        group: sam
        mode: "0400"
      when: inventory_hostname == "node02"
	  
---
- name: Copy text files to Appservers
  hosts: all
  become: yes
  tasks:
    - name: Copy blog.txt to stapp01
      ansible.builtin.copy:
        src: /usr/src/dba/blog.txt
        dest: /opt/dba/
        owner: tony
        group: tony
        mode: "0755"
      when: inventory_hostname == "stapp01"
    - name: Copy story.txt to stapp02
      ansible.builtin.copy:
        src: /usr/src/dba/story.txt
        dest: /opt/dba/
        owner: steve
        group: steve
        mode: "0755"
      when: inventory_hostname == "stapp02"
	  
	 
---
- name: Create and Copy arch file to Appservers
  hosts: all
  become: yes
  tasks:
    - name: Copy demo.tar.gz to stapp01
      ansible.builtin.archive:
        #path: /usr/src/security/
        #or number of files
        path:
         - /root/file1.txt
         - /usr/local/share/file2.txt
         - /var/log/lastlog
        dest: /opt/security/demo.tar.gz
        owner: tony
        group: tony
        mode: "0755"
      when: inventory_hostname == "stapp01"
	  
#to check results
# ansible all -a "ls -ltr /opt/security/" -i inventory