---
- hosts: web1
  become: true
  tasks:
    - name: block 161/udp port on web1 node permanently 
      firewalld:
        port: 161/udp
        zone: block
        permanent: yes
        state: enabled
        immediate: yes

---
- hosts: web1
  tasks:
    - name: Enable HTTPS for ansible controller
      firewalld:
        source: 172.20.1.2
        service: https
        zone: internal
        state: enabled
        permanent: yes

    - service:
        name: firewalld
        state: reloaded