# ansible-playbook web.yml -i inventory | grep distribution
---
- name: Get and print facts from the hosts
  hosts: all
  tasks:
    - debug:
        var: ansible_facts

---
- hosts: db1
  gather_facts: True
  tasks:
    - name: Get server architecture
      debug:
        var: ansible_facts.architecture #moving to the next level in list of facts

#or using terminal command
# ansible -m setup localhost #gather ansible_facts from localhost

---
- hosts: node02
  gather_facts: True
  become: yes
  tasks:
    - name: Create facts file
      blockinfile:
        create: true
        path: /root/facts.txt
        block: |
          This is Ansible managed node {{ ansible_nodename }}
          IP address of host is {{ ansible_default_ipv4.address }}
          Its OS family is {{ ansible_os_family }}
        state: present