#roles

#to create a role
# ansible-galaxy init [role_name]

# to lists roles
# ansible-galaxy list

# to install a role from role repository
# ansible-galaxy install [role_name] -p ./roles - to install it under current folder

#role structure
# README.md
# templates
# tasks
# handlers
# vars
# defaults
# meta

# roles path
# /etc/ansible/ansible.cfg
# roles_path = /etc/ansible/roles

---
- hosts: all
  become: true
  roles:
    - [role_name]

---
- hosts: all
  become: true
  roles:
    - role: mysql_role #to provide more custom settings
      become: yes
