#There is already an inventory file ~/playbooks/inventory on jump host.
#a. Add all users given in the users.yml file on app server 3.
#b. Also add developers and admins groups on the same server.
#c. As per the list given in the users.yml file, make each user member of the respective group they are listed under.
#d. Make sure home directory for all of the users under developers group is /var/www (not the default i.e /var/www/{USER}).
#Users under admins group should use the default home directory (i.e /home/devid for user devid).
#e. Set password GyQkFRVNr3 for all of the users under developers group and TmPcZjtRQx for of the users under admins group.
#Make sure to use the password given in the ~/playbooks/secrets/vault.txt file as Ansible vault password to encrypt the original password strings.
#You can use ~/playbooks/secrets/vault.txt file as a vault secret file while running the playbook (make necessary changes in ~/playbooks/ansible.cfg file).
#f. All users under admins group must be added as sudo users. To do so, simply make them member of the wheel group as well.

#inventory
#stapp01 ansible_host=172.16.238.10 ansible_ssh_pass=Ir0nM@n ansible_user=tony
#stapp02 ansible_host=172.16.238.11 ansible_ssh_pass=Am3ric@ ansible_user=steve
#stapp03 ansible_host=172.16.238.12 ansible_ssh_pass=BigGr33n ansible_user=banner

# /etc/ansible/ansible.cfg
#[defaults]
#host_key_checking = False
#vault_password_file = ~/playbooks/secrets/vault.txt

#./data/users.yaml
#admins:
#  - rob
#  - david
#  - joy

#developers:
#  - tim
#  - ray
#  - jim
#  - mark

#./secrets/vault.txt
#P@ss3or432

#Create vault password for admins and developers
# ansible-vault encrypt_string 'password_here'
# ansible-vault encrypt_string 'password_here'

---
- hosts: stapp03
  become: true
  vars:
    admin_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64396331383031323064343432353935323334626437666531313633343232353936323738313337
          3436666266356534343934653132363866626231636663610a663731653135316132613831323463
          61663331626236303163306234353632643231353036323833373865346531306331613761356665
          3365653631656530310a626332643537333861653335643836646566323934653362333364386137
          3731
    developer_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63613761313339646563643435326633313066303030666266393232646137343065376530363933
          3034353231653239656332363661346337353836666130370a613366646565373431343932633337
          34666430376264386137326632626637383630383262333330376661656266393665386337326465
          3165366632623865660a363866653237386163653636373764626334303631333062623762396235
          6630
  tasks:
    - name: Include user details from file
      include_vars:
        file: ./data/users.yml

    - name: Create groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - admins
        - developers

    - name: Create and set admin passwords
      user:
        name: "{{ item }}"
        password: "{{ admin_pass | string | password_hash('sha512') }}"
        groups: admins, wheel
      with_items: "{{ admins }}"
      when: admins is defined

    - name: Create and set developer passwords
      user:
        name: "{{ item }}"
        password: "{{ developer_pass | string | password_hash('sha512') }}"
        groups: developers
        home: /var/www/
      with_items: "{{ developers }}"
      when: developers is defined