Create a playbook facts.yml under ~/playbooks directory on Ansible controller.
In this playbook using blockinfile module create
a file facts.txt under /root on node02 host and add below given block in it.
You will need to enable facts gathering for this task.

This is Ansible managed node `<hostname-of-host> `
IP address of host is `<ip-address-of-host>`
Its OS family is `<os-family>`
After that make a copy of this file as index.html under /usr/share/nginx/html/

---
- hosts: node02
  gather_facts: True
  become: yes
  tasks:
    - name: Create facts file
      blockinfile:
        create: true
        path: /root/facts.txt
        block: |
          This is Ansible managed node {{ ansible_nodename }}
          IP address of host is {{ ansible_default_ipv4.address }}
          Its OS family is {{ ansible_os_family }}
        state: present

    - name: Copy file as html
      copy:
        src: /root/facts.txt
        remote_src: yes
        dest: /usr/share/nginx/html/index.html


---
#check
ansible node02 -a "cat /usr/share/nginx/html/index.html" -i inventory