#dirs
#inventory -> inventory
#inventory content
# web1 
# web2 
# web3
# [web_servers]
# web1
# web2
# web3
#
#inventory -> host_vars -> web1.yml \ web2.yml ... same name as host
#web1.yml content
# ansible_host: 172.16.238.10
# ansible_ssh_pass: Ir0nM@n
# ansible_user: tony
#
#inventory -> group_vars -> web_servers.yml - sane name as group
#web_servers.yml content
# dns_server: 10.1.1.15



#variables

- hosts: all
  tasks:
     - shell: uptime
       register: uptime_result

     - debug: var=uptime_result.stdout #print results of shell command

---
- hosts: all
  gather_facts: no
  tasks:
    - name: stat module help to find the file info
      stat:
        path: /var/run
      register: your_variable

    # for your reference, check the outputs of these
    - debug: var=your_variable.stat

    # your code goes here...
    - shell: echo "{{your_variable.stat}}" > /tmp/by_ansible
	
	
---
- name: help me fix it playbook
  hosts: all
  gather_facts: yes
  tasks:
    - name: alternative way to gather facts about remote host
      setup: filter='ansible_dist*'
      register: facts
    - debug: var=facts.ansible_facts.ansible_distribution # or - debug: msg="{{ facts }}"
    - shell: echo "{{facts.ansible_facts.ansible_distribution}}" > /tmp/output.txt

#magic variables

#inventory 
#node00.host ansible_host=172.20.1.100 ansible_ssh_pass=Passw0rd ansible_user=root
#node01.host ansible_host=172.20.1.101 ansible_ssh_pass=Passw0rd ansible_user=root dns_server=8.8.8.8
---
- hosts: all
  become: true
  tasks:
    - name: magic variable - print dns server from node01 for all nodes
      shell: "echo {{hostvars['node01.host'].dns_server}} >> /tmp/variable.txt"


#custom file for vars
---
- hosts: all
  tasks:
     - include_vars:
         file: /opt/tmp/file.yml
         name: file_name

     - shell: echo {{ file_name }}
       register: echo_result

     - debug: var=echo_result.stdout #print results of shell command

#include tasks from separate folder
---
- name: Configure full stack server
  hosts: f-server-1
  gather_facts: no
  tasks:
    - include_tasks: tasks/install-db-server.yml
    - include_tasks: tasks/install-web-server.yml

- name: 5563947-Install dependencies
  yum:
    enablerepo: extras
    name:
      - epel-release
    state: installed

#content of tasks/install-web-server.yml
- name: 5563947-Install dependencies
  yum:
    name:
      - python-pip
    state: installed
- name: 5563948-Install Python Flask dependencies
  pip:
    name:
      - flask
      - flask-mysql
    state: present
- name: Copy web-server code
  copy: src=app.py dest=/opt/app.py
- name: Start web-application
  shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &



